FROM ghcr.io/carpentries-incubator/intro-to-modern-fortran:main

COPY --chown=vscode exercises/01-trivial-program /home/vscode/01-trivial-program

WORKDIR /home/vscode/01-trivial-program

# Build exercise
RUN gfortran hello_world.f90 -o hello_world
# Run exercise
RUN ./hello_world
