# Based on https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
---
name: "Build and publish parent docker image for the exercises"

on:
  # Allow manual execution for testing, hot-fixes, etc
  workflow_dispatch:
    inputs:
      push_to_registry:
        description: 'Push the image to the GitHub Container Registry'
        required: false
        default: true
        type: boolean
  # Build on pushes and PRs to main if relevant files have changed
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/docker_build_parent_exercises_image.yaml'
      - '.devcontainer/Dockerfile'
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths:
      - '.github/workflows/docker_build_parent_exercises_image.yaml'
      - '.devcontainer/Dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: modern-fortran

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: always.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-parent-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # Ensure there is enough space for building the large docker image
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        with:
          large-packages: false

      - name: Build and push to ghcr
        uses: connoraird/build-push@7534f5515ccd15ee932fd925b9f1935efbbb3fdd # v1.0.1
        with:
          dockerfile_path: ./.devcontainer/Dockerfile
          image_name: ${{ env.IMAGE_NAME }}
          tags: |
            latest
            type=ref,event=branch
          context: .
          push_to_registry: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.push_to_registry) }}
          registry_address: ${{ env.REGISTRY }}
          registry_username: ${{ github.actor }}
          registry_password: ${{ github.token }}
